name: Update index.html from GitBook Docs

on:
  schedule:
    - cron: "0 * * * *"  # Runs at the top of every hour
  workflow_dispatch:    # Allows manual trigger

permissions:
  contents: write

jobs:
  update-index:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Reset local branch to remote state
        run: |
          git fetch origin
          git reset --hard origin/main

      - name: Download GitBook Docs Content and save as index.html
        run: |
          curl -L https://h3rmes.gitbook.io/h3rmes-docs/ -o index.html

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add index.html
          git commit -m "Update index.html from GitBook Docs [Automated]" || echo "No changes to commit"
          git push --force-with-lease origin main
